services:
  frontend:
    build: ../services/frontend
    command: bash -lc "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - ../services/frontend:/app
      - frontend_db:/app/db
    working_dir: /app
    environment:
      - DJANGO_SETTINGS_MODULE=frontend.settings
      - COMMENTS_BASE_URL=http://comments:8002
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}

  users:
    build: ../services/users
    command: bash -lc "python manage.py migrate && python manage.py runserver 0.0.0.0:8001"
    ports:
      - "8001:8001"
    volumes:
      - ../services/users:/app
      - users_db:/app/db
    working_dir: /app
    environment:
      - DJANGO_SETTINGS_MODULE=users_service.settings

  comments:
    build: ../services/comments
    command: bash -lc "python manage.py migrate && python manage.py runserver 0.0.0.0:8002"
    ports:
      - "8002:8002"
    volumes:
      - ../services/comments:/app
      - comments_db:/app/db
    working_dir: /app
    environment:
      - DJANGO_SETTINGS_MODULE=comments_service.settings

volumes:
  frontend_db:
  users_db:
  comments_db:


