services:
  frontend:
    image: kumovish/comment-frontend:latest
    command: bash -lc "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=frontend.settings
      - COMMENTS_BASE_URL=http://comments:8002
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
    depends_on:
      - comments
      - users

  users:
    image: kumovish/comment-users:latest
    command: bash -lc "python manage.py migrate && python manage.py runserver 0.0.0.0:8001"
    ports:
      - "8001:8001"
    environment:
      - DJANGO_SETTINGS_MODULE=users_service.settings

  comments:
    image: kumovish/comment-comments:latest
    command: bash -lc "python manage.py migrate && python manage.py runserver 0.0.0.0:8002"
    ports:
      - "8002:8002"
    environment:
      - DJANGO_SETTINGS_MODULE=comments_service.settings
